CRUD tutorial doc update
ciscoheat/superforms-web pull request #19
Opened 2023-07-22 19:21 UTC by lolcabanon

Enhanced and corrected the awesome CRUD tutorial to make it easier to follow!

2023-07-22 19:55 UTC, ciscoheat requested changes

2023-07-22 19:55 UTC, ciscoheat commented on src/routes/crud/+page.md
> +  id: z.string().regex(/^\\d+$/),
No need for double backslashes, can you revert that? Otherwise, very nice, much appreciated! :)

2023-07-23 04:46 UTC, lolcabanon commented on src/routes/crud/+page.md
> +  id: z.string().regex(/^\\d+$/),
When renderer the backslash was not there! It is a markdown escaping so it will render to `/^\d+$/` as expected :)

![Screenshot_20230723-064310__01.jpg](https://github.com/ciscoheat/superforms-web/assets/90099349/151e08fd-2510-4185-bcab-f4cc09cdaa69)

2023-07-23 04:57 UTC, lolcabanon commented on src/routes/crud/+page.md
> +  id: z.string().regex(/^\\d+$/),
I had a hard time figuring this one out actually! 

Since the ID is hidden I had no error message showing, but I knew the form was invalid. I added one to all schema fields and then found the ID was invalid but I couldn't see how... Then I went on regexr.com and finally got it! The only match was actually "d" one or more times... 😂 

**Thanks for making an awesome form library btw!**

Fun fact, I am currently travelling in Sweden and just started using it and saw on your profile you are swedish. Hej hej! 😊

2023-07-23 09:23 UTC, ciscoheat commented on src/routes/crud/+page.md
> +  id: z.string().regex(/^\\d+$/),
Oh, that's annoying, not being able to just copy/paste code to markdown. Thanks for letting me know about this, will merge now! 

What a fun coincidence with Sweden, I hope it will be a nice stay!

2023-07-23 09:23 UTC, merged